apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-kubernetes-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-kubernetes-argocd
  template:
    metadata:
      labels:
        app: nginx-kubernetes-argocd
    spec:
      containers:
      - name: nginx-kubernetes-argocd
        image: liyakatahmed/nginx-custom-index-html
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-kubernetes-argocd
spec:
  type: NodePort
  selector:
    app: nginx-kubernetes-argocd
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000