apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-kubernetes-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-kubernetes-argocd
  template:
    metadata:
      labels:
        app: nginx-kubernetes-argocd
    spec:
      containers:
      - name: nginx-kubernetes-argocd
        image: liyakatahmed/nginx-kubernetes-argocd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80